module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#c7c4d8",
        outline: "#918fa1",
        "outline-variant": "#464555",
        "surface-tint": "#c3c0ff",
        primary: "#c3c0ff",
        "on-primary": "#1d00a5",
        "primary-container": "#4f46e5",
        "on-primary-container": "#dad7ff",
        secondary: "#4edea3",
        "on-secondary": "#003824",
        tertiary: "#ffb95f",
        error: "#ffb4ab",
        "on-background": "#dae2fd",
      },
      fontFamily: {
        geist: ["Geist", "Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.1" }],
        "display-lg": ["48px", { lineHeight: "1.1" }],
        "headline-lg": ["32px", { lineHeight: "1.2" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
        "body-md": ["16px", { lineHeight: "1.6" }],
        "label-sm": ["12px", { lineHeight: "1" }],
        code: ["14px", { lineHeight: "1.5" }],
      },
    },
  },
  plugins: [],
};
